In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [66]:
data_normal = pd.read_csv('/home/alex/VM_and_Data/Code/bci-notes/content/data_normal.csv')
data_mismatch = pd.read_csv('/home/alex/VM_and_Data/Code/bci-notes/content/data_mismatch.csv')
print(data_normal.head())
print(data_mismatch.head())

#ls_duplets = list(data_normal['sequence'])
for triplet in data_mismatch['sequence'][:1]:
	ls = list(triplet)
	pairs_of_triplets = [("".join([ls[0], ls[1],'/', ls[4], ls[5]]), "".join([ls[1], ls[2], '/', ls[5], ls[6]])),
					 ("".join([ls[0], ls[1],'/', ls[4], ls[5]][::-1]), "".join([ls[1], ls[2], '/', ls[5], ls[6]][::-1]))]
	pairs_of_duplets = []
	duplets_matrix = np.column_stack((data_normal['sequence'].T,data_normal['sequence'].T))
	print(duplets_matrix)
	print(pairs_of_triplets)

	mask = np.zeros(duplets_matrix.shape, dtype=bool)
	mask[:, 0] = duplets_matrix[:,0] == (pairs_of_triplets[0][0] or pairs_of_triplets[1][0])
	mask[:, 1] = duplets_matrix[:,1] == (pairs_of_triplets[0][1] or pairs_of_triplets[1][0])
	print(mask,'\n')
print(data_normal.iloc[1,1])

''' 
def min_P_error(norm, mismatch):
	G_norm = data_normal['dG_37_unified']
	G_mismatch = data_mismatch['dG_37']
	G_max = G_mismatch - G_norm
	P = np.exp(-G*const)/(1 + np.exp(-G*const))
	'''

  sequence  dG_37_unified
0    AA/TT          -1.00
1    AT/TA          -0.88
2    TA/AT          -0.58
3    CA/GT          -1.45
4    GT/CA          -1.44
  sequence  dG_37
0  ACC/TTG   1.62
1  CCC/GTG   1.60
2  GCA/CTT   1.37
3  GCC/CTG   1.60
4  GCG/CTC   1.02
[['AA/TT' 'AA/TT']
 ['AT/TA' 'AT/TA']
 ['TA/AT' 'TA/AT']
 ['CA/GT' 'CA/GT']
 ['GT/CA' 'GT/CA']
 ['CT/GA' 'CT/GA']
 ['GA/CT' 'GA/CT']
 ['CG/GC' 'CG/GC']
 ['GC/CG' 'GC/CG']
 ['GG/CC' 'GG/CC']]
[('AC/TT', 'CC/TG'), ('TT/CA', 'GT/CC')]
[[False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]] 

-0.88


" \ndef min_P_error(norm, mismatch):\n\tG_norm = data_normal['dG_37_unified']\n\tG_mismatch = data_mismatch['dG_37']\n\tG_max = G_mismatch - G_norm\n\tP = np.exp(-G*const)/(1 + np.exp(-G*const))\n\t"

In [8]:
np.concatenate((data_normal['dG_37_unified'], data_mismatch['dG_37']))

array([-1.  , -0.88, -0.58, -1.45, -1.44, -1.28, -1.3 , -2.17, -2.24,
       -1.84,  1.62,  1.6 ,  1.37,  1.6 ,  1.02,  1.35,  1.95,  1.39,
        1.04,  1.37,  1.37,  1.02,  1.35,  1.72,  1.37,  1.7 ])

In [5]:
ar_1 = np.array([6,7,8])
ar_2 = np.array([5,6,7])
ar_sum = np.concatenate((ar_1, ar_2))
ar_sum



array([6, 7, 8, 5, 6, 7])

In [22]:
ar_1[(ar_1 >= 7)]

array([7, 8])

In [24]:
'AA/R' == 'AA/G'

False

In [62]:
triple = data_mismatch['sequence'][0]
ls = list(triple)
print(ls)
print("".join([ls[0], ls[1],'/', ls[4], ls[5]]))
print("".join([ls[0], ls[1],'/', ls[4], ls[5]][::-1]))


['A', 'C', 'C', '/', 'T', 'T', 'G']
AC/TT
TT/CA


In [59]:
k = [5,6][::-1]
print(k)

[6, 5]


In [ ]:
data_normal = pd.read_csv('/home/alex/VM_and_Data/Code/bci-notes/content/data_normal.csv')
data_mismatch = pd.read_csv('/home/alex/VM_and_Data/Code/bci-notes/content/data_mismatch.csv')
print(data_normal.head())
print(data_mismatch.head())
print(type(data_normal['dG_37_unified']))

def min_P_error(norm, mismatch):
	G_norm = data_normal['dG_37_unified']
	G_mismatch = data_mismatch['dG_37']
	G_max = G_mismatch - G_norm
	P = np.exp(-G*const)/(1 + np.exp(-G*const))

In [ ]:
import math

# 1. Таблица 1: Триплеты с миссмэтчем C-T/C-A/C-C (dG_37 в ккал/моль)
# Формат: верхняя нить 5'-XYZ-3' -> нам важен только сам триплет XYZ
MISMATCH_TRIMERS = {
    "ACC": 1.62, "CCC": 1.60, "GCA": 1.37, "GCC": 1.60,
    "GCG": 1.02, "GCT": 1.35, "TCC": 1.95, "ACA": 1.39,
    "ACG": 1.04, "ACT": 1.37, "CCA": 1.37, "CCG": 1.02,
    "CCT": 1.35, "TCA": 1.72, "TCG": 1.37, "TCT": 1.70
}

# 2. Таблица 2: Идеальные Уотсон-Криковские дуплеты (Unified, ккал/моль)
# Сразу разворачиваем симметрию на все 16 возможных динуклеотидов
WC_DOUBLETS = {
    "AA": -1.00, "TT": -1.00,
    "AT": -0.88,
    "TA": -0.58,
    "CA": -1.45, "TG": -1.45,
    "GT": -1.44, "AC": -1.44,
    "CT": -1.28, "AG": -1.28,
    "GA": -1.30, "TC": -1.30,
    "CG": -2.17,
    "GC": -2.24,
    "GG": -1.84, "CC": -1.84
}

RT = 0.616  # RT при 37 C (310.15 K) в ккал/моль

results = []

# 3. Основной цикл расчета
for trimer, dg_mismatch in MISMATCH_TRIMERS.items():
    # Разбиваем триплет XYZ на два шага: XY и YZ
    step1 = trimer[0:2]
    step2 = trimer[1:3]
    
    # Считаем энергию идеального комплементарного триплета
    dg_correct = WC_DOUBLETS[step1] + WC_DOUBLETS[step2]
    
    # Находим цену ошибки (Delta Delta G)
    ddg = (dg_mismatch - dg_correct)* 4184 / (6.02 * 10**23)
    
    # Считаем вероятность ошибки по Больцману
    const = 1/(1.380649*(10**(-23))*273)
    p_error = math.exp(-ddg * const)
    
    results.append({
        "trimer": trimer,
        "dg_mismatch": dg_mismatch,
        "dg_correct": dg_correct,
        "ddg": ddg,
        "p_error": p_error
    })

# 4. Сортируем по вероятности ошибки (от минимальной к максимальной)
results_sorted = sorted(results, key=lambda x: x["p_error"])

min_case = results_sorted[0]
max_case = results_sorted[-1]
mean_error = np.mean(results_sorted)

print("=== МИНИМАЛЬНАЯ ВЕРОЯТНОСТЬ ОШИБКИ ===")
print(f"Триплет: {min_case['trimer']} | dG_mismatch = {min_case['dg_mismatch']} | dG_correct = {min_case['dg_correct']:.2f}")
print(f"Delta Delta G = {min_case['ddg']} | P_error = {min_case['p_error']:.2e}\n")

print("=== МАКСИМАЛЬНАЯ ВЕРОЯТНОСТЬ ОШИБКИ ===")
print(f"Триплет: {max_case['trimer']} | dG_mismatch = {max_case['dg_mismatch']} | dG_correct = {max_case['dg_correct']:.2f}")
print(f"Delta Delta G = {max_case['ddg']} | P_error = {max_case['p_error']:.2e}")

=== МИНИМАЛЬНАЯ ВЕРОЯТНОСТЬ ОШИБКИ ===
Триплет: GCC | dG_mismatch = 1.6 | dG_correct = -4.08
Delta Delta G = 3.9476943521594687e-20 | P_error = 2.83e-05

=== МАКСИМАЛЬНАЯ ВЕРОЯТНОСТЬ ОШИБКИ ===
Триплет: ACT | dG_mismatch = 1.37 | dG_correct = -2.72
Delta Delta G = 2.8426179401993357e-20 | P_error = 5.30e-04
